kind: pipeline
name: default

steps:
- name: publish
  image: plugins/docker
  settings:
    repo: yoyostile/rheinpegel-exporter
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
    - ${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:8}
    - ${DRONE_COMMIT_BRANCH}-latest
